### ISSUE TITLE
store.js does not exist

### ISSUE THREAD

**Issue by Invincible1996** [QianmiOpen/iflux2#11]
![image](https://user-images.githubusercontent.com/22675676/41225142-bb53f8a0-6da0-11e8-8be5-1361c0f8ee1b.png)

**Comment by hufeng** [comment]
ReactNative can not find react-dom module
这是什么原因呢？因为我们的 store 模块依赖了 react-dom，在 react-native 的环境是没有 react-dom 这个模块，所以请使用我们的一个自定义的 babel 插件来解决问题。

yarn add babel-plugin-transform-rn-react-dom
//.babelrc
{
  "plugins": [
    "transform-rn-react-dom"
  ]
}
