### ISSUE TITLE
@Action装饰的函数的函数名无意义

### ISSUE THREAD

**Issue by dr2009** [QianmiOpen/iflux2#7]
`@action`装饰的函数的函数名无意义,
是否可以直接使用改函数的函数名作为@Action的参数

before
```
@Action('start')
increment(state) {
    return state.update('time', time => time + 1)
}
```

after
```
@Action
start(state) {
    return state.update('time', time => time + 1)
}
```

**Comment by hufeng** [comment]
@dr2009  其实是有意义的，因为这样更灵活, 不受限于函数名字的命名规则，比如，我的事件名称可能更具有语义化

```js
@Action('loading:end')
```

另外，还有一个问题是，在uglify或者gzip的时候，可以会把函数的名称简化掉，比如变成a方法

那你的dispatch('start') // 就找不到actor的method可以处理了。

**Comment by dr2009** [comment]
@hufeng 
1. 函数名字的命名规则
参考 redux的做法 ，也可以随意命名
```
const LOADING_END= 'loading:end'

@Action
[LOADING_END]() {
   // xxx 
}
```

2. 压缩问题
mobx中是可以的，应该可以处理。
```
@action 
XXX (){
  // xxx
}
```

不过上面的设置变量，保持引用。应该不会被压缩吧。没有测试过

不过好像定义变量那么写，也是很繁琐，多了一步，不如直接这么干吧。

**Comment by hufeng** [comment]
如果在这样的话，连@Action都不需要 直接写方法名就可以了

**Comment by hufeng** [comment]
我再考虑下

**Comment by hufeng** [comment]
[LOADING_END] {
   // xxx 
}

代码写起来有点不够优雅

**Comment by dr2009** [comment]
@hufeng 

刚刚我也觉得是繁琐的了。不过多出来的函数名。我也怪难受的。

不过redux 这么定义ActionType, 是为集中管理ActionType，也有好处。
