### ISSUE TITLE
Store 中的action 和 @actor 中的@Action 命名

### ISSUE THREAD

**Issue by dr2009** [QianmiOpen/iflux2#8]
Store实例中的相关函数感觉应该是flux架构的action
@actor 中的@Action感觉应该是flux架构中的dispatcher

有点饶人^_^,让我混淆。

**Comment by hufeng** [comment]
Store实例中的相关函数感觉应该是flux架构的action ----[YES]
store中的dispatch 是 flux中的dispatcher
@Action 是dispatch的回调
